version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: rca_postgres
    restart: always
    environment:
      POSTGRES_USER: rca_user
      POSTGRES_PASSWORD: rca_secret_2024
      POSTGRES_DB: rca_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./infra/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: rca_redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  pgdata:
